In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
print(a)

[ 0.03075036 -1.86327403 -0.8247813   1.79451465 -0.46410181]


In [3]:
print(a.T)

[ 0.03075036 -1.86327403 -0.8247813   1.79451465 -0.46410181]


In [4]:
print(np.dot(a, a.T))

7.588673197140454


In [6]:
a = np.random.randn(5, 1)
print(a)

[[-0.54267385]
 [-1.54730168]
 [-0.61913396]
 [ 2.24371566]
 [ 1.30336844]]


In [7]:
print(a.T)

[[-0.54267385 -1.54730168 -0.61913396  2.24371566  1.30336844]]


In [8]:
print(np.dot(a, a.T))

[[ 0.29449491  0.83968016  0.33598781 -1.21760583 -0.70730397]
 [ 0.83968016  2.39414248  0.95798702 -3.47170501 -2.01670417]
 [ 0.33598781  0.95798702  0.38332686 -1.38916057 -0.80695966]
 [-1.21760583 -3.47170501 -1.38916057  5.03425997  2.92438817]
 [-0.70730397 -2.01670417 -0.80695966  2.92438817  1.69876928]]
