In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
print(a)

[ 0.03075036 -1.86327403 -0.8247813   1.79451465 -0.46410181]


In [3]:
print(a.T)

[ 0.03075036 -1.86327403 -0.8247813   1.79451465 -0.46410181]


In [4]:
print(np.dot(a, a.T))

7.588673197140454


In [6]:
a = np.random.randn(5, 1)
print(a)

[[-0.54267385]
 [-1.54730168]
 [-0.61913396]
 [ 2.24371566]
 [ 1.30336844]]


In [7]:
print(a.T)

[[-0.54267385 -1.54730168 -0.61913396  2.24371566  1.30336844]]


In [8]:
print(np.dot(a, a.T))

[[ 0.29449491  0.83968016  0.33598781 -1.21760583 -0.70730397]
 [ 0.83968016  2.39414248  0.95798702 -3.47170501 -2.01670417]
 [ 0.33598781  0.95798702  0.38332686 -1.38916057 -0.80695966]
 [-1.21760583 -3.47170501 -1.38916057  5.03425997  2.92438817]
 [-0.70730397 -2.01670417 -0.80695966  2.92438817  1.69876928]]


In [13]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
print(a)
print(b)
a + b.T

[[-0.09843485  0.6163623   0.16175047 -0.76251079]
 [ 0.19824628  0.24284276  0.5690304   0.3040784 ]
 [ 0.98766836 -1.28757795 -0.31242771  0.10795121]]
[[ 0.18889931]
 [-1.16684472]
 [-0.64464779]
 [ 0.62859817]]


array([[ 0.09046447, -0.55048242, -0.48289732, -0.13391262],
       [ 0.38714559, -0.92400196, -0.07561739,  0.93267657],
       [ 1.17656767, -2.45442267, -0.9570755 ,  0.73654938]])

In [18]:
a=np.array([[2,1],[1,3]])
a*a

array([[4, 1],
       [1, 9]])